### ISSUE TITLE
Generated mod.json does not keep dependency version specifications

### ISSUE THREAD

**Issue by kodenamekrak** [QuestPackageManager/QPM.CLI#18]
When running `qpm-rust qmod build`, the outputted mod.json file dependencies will have their versions set to `=` regardless of what was specified in `qpm.json`

![image](https://user-images.githubusercontent.com/106346717/213872464-b37e5729-2e4e-4f79-8fed-94a777b159ad.png)

**Comment by Fernthedev** [comment]
For documentation purposes, as the issue might remain for some time unresolved, I'm assuming this is the cause of the issue
https://github.com/QuestPackageManager/QPM.CLI/blob/069502952e6e2bf7ada906e5add25b4ad01a1f3a/src/models/package.rs#L77-L80

Will have to dig deeper to see how to properly resolve this
