### ISSUE TITLE
adb does not work without AdbWinApi.dll

### ISSUE THREAD

**Issue by raineio** [QuestPackageManager/QPM.CLI#37]
QPM does not currently give all of the Android SDK to work with, just `adb.exe`, which makes it impossible to use adb. The Windows release of the Android SDK comes with the required platform tools for adb to work on any given platform.

**Comment by Fernthedev** [comment]
Should be resolved with https://github.com/QuestPackageManager/QPM.CLI/commit/15e57af5b4ee6c41bfd2221c722797943a927d0d
