### ISSUE TITLE
Feature: Update version of existing dependency

### ISSUE THREAD

**Issue by kodenamekrak** [QuestPackageManager/QPM.CLI#46]
Currently updating a dependency version requires either editing `qpm.json` manually, or removing and re-adding the dependency. It would be nice to have a command such as `qpm dependency update ...` with an optional version specifier, or changing `qpm dependency add` to modify the existing dependency rather than adding a new one and causing duplicate dependencies with the same ID.

**Comment by Fernthedev** [comment]
This is already the case

https://github.com/QuestPackageManager/QPM.CLI/commit/9b851395c197d6afec901c94575edcf38d5c97be

**Comment by Fernthedev** [comment]
Verified with #47
